// src/app/components/miscellaneous-components/pages-components/menu/menu.component.ts
import { Component } from '@angular/core';
import {RouterLink, RouterLinkActive} from "@angular/router";
import {CommonModule} from "@angular/common";

@Component({
  selector: 'app-menu',
  standalone: true,
  imports: [
    RouterLink,
    RouterLinkActive
  ],
  templateUrl: './menu.component.html',
  styleUrl: './menu.component.scss'
})
export class MenuComponent {

}

<nav id="navbar" class="navbar navbar-expand-lg bg-body-tertiary p-0">
  <div id="container-nav" class="container-fluid">
    <a class="navbar-brand" routerLink="/home" routerLinkActive="active">
      <img id="logo-menu" src="logo.png" alt="logo">
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#basic-navbar-nav"
      aria-controls="nbasic-navbar-nav"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="basic-navbar-nav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown basic-nav-dropdown">
          <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Para você
          </a>
          <ul class="dropdown-menu">
            <div>
              <h6>Conta</h6>
              <li><a class="dropdown-item" href="#">Conta Digital</a></li>
              <li><a class="dropdown-item" href="#">Cartão de Crédito</a></li>
              <li><a class="dropdown-item" href="#">Rendimentos</a></li>
            </div>
            <div>
              <h6>Empréstimos</h6>
              <li><a class="dropdown-item" href="#">Antecipação FGTS</a></li>
              <li><a class="dropdown-item" href="#">Empréstimo Consignado</a></li>
              <li><a class="dropdown-item" href="#">Empréstimo Pessoal</a></li>
            </div>
          </ul>
        </li>
        <li class="nav-item dropdown basic-nav-dropdown about">
          <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Sobre o Nex
          </a>
          <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Sobre nós</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown basic-nav-dropdown about">
          <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Ajuda
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Fale com a gente</a></li>
            <li><a class="dropdown-item" href="#">Ouvidoria</a></li>
          </ul>
        </li>
      </ul>
      <div id="button-div">
        <a routerLink="/login" routerLinkActive="active">
          <button id="user-access">
            <p class="m-0">Acesse sua conta</p>
          </button>
        </a>
      </div>
    </div>
  </div>
</nav>

// src/components/Menu.jsx
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import NavDropdown from 'react-bootstrap/NavDropdown';
import { Link } from 'react-router-dom';

export default function Menu() {
    return (
        <>
            <Navbar id="navbar" expand="lg" className="bg-body-tertiary p-0">
                <Container id="container-nav">
                    <Navbar.Brand href="#home">
                        <img id="logo-menu" src="logo.png" alt="logo"></img>
                    </Navbar.Brand>
                    <Navbar.Toggle aria-controls="basic-navbar-nav" />
                    <Navbar.Collapse id="basic-navbar-nav">
                    <Nav>
                        <NavDropdown title="Para você" id="basic-nav-dropdown">
                            <div>
                                <h6>Conta</h6>
                                <NavDropdown.Item href="#action/3.1">Conta Digital</NavDropdown.Item>
                                <NavDropdown.Item href="#action/3.2">Cartão de Crédito</NavDropdown.Item>
                                <NavDropdown.Item href="#action/3.3">Rendimentos</NavDropdown.Item>
                            </div>
                            <div>
                                <h6>Empréstimos</h6>
                                <NavDropdown.Item href="#action/3.1">Antecipação FGTS</NavDropdown.Item>
                                <NavDropdown.Item href="#action/3.2">Empréstimo Consignado</NavDropdown.Item>
                                <NavDropdown.Item href="#action/3.3">Empréstimo Pessoal</NavDropdown.Item>
                            </div>
                        </NavDropdown>
                        <NavDropdown title="Sobre o Nex" id="basic-nav-dropdown" className="about">
                            <NavDropdown.Item href="#action/3.1">Sobre nós</NavDropdown.Item>
                        </NavDropdown>
                        <NavDropdown title="Ajuda" id="basic-nav-dropdown" className="about">
                            <NavDropdown.Item href="#action/3.1">Fale com a gente</NavDropdown.Item>
                            <NavDropdown.Item href="#action/3.3">Ouvidoria</NavDropdown.Item>
                        </NavDropdown>
                    </Nav>
                    <div id="button-div">
                        <Link to={"/login"}>
                            <button id="user-access">Acesse sua conta</button>
                        </Link>
                    </div>
                    </Navbar.Collapse>
                </Container>
            </Navbar>
        </>
    );
}
